import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import ThemeProvider from "@/RTK/slices/theme/themeProvider";
import StoreProvider from "@/RTK/slices/theme/storeProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <ThemeProvider >
        <body className="wrapper">
          <Header />
          <div className="container">
            {children}
          </div>
          <Footer />
        </body>
      </ThemeProvider>
    </StoreProvider >

  );
}
